""" Time-Causal Bandpass Representation Toolbox for Python

For decomposing a signal into (i) the time-causal bandpass representation
constructed from differences between temporal scale-space representations
generated by convolution with discrete approximations of the time-causal
limit kernel (DoT),

as well as comparing to (ii) the non-causal bandpass representation
constructed from differences between non-causal scale-space representations
generated by convolution with the discrete analogue of the Gaussian
kernel (DoG)

and comparing to (iii) the time-causal bandpass representation
constructed from differences between scale channels constructed
from smoothing with discrete approximations of single truncated
exponential kernels in terms of first-order recursive filters.

References:

Lindeberg (2025) "Time-causal and time-recursive wavelets",
arXiv preprint 2510.05834.

Lindeberg (2023) "A time-causal and time-recursive temporal scale-space 
representation of temporal signals and past time", 
Biological Cybernetics 117(1-2): 21-59.
"""

from math import log, ceil, sqrt
import numpy as np
from scipy.signal import lfilter
from pyscsp.discscsp import discgaussconv
from pytempscsp.tempscsp import limitkernfilt_mult


def bandpass_DoT(
        signal,
        stddevmin: float,
        stddevmax: float,
        c: float = 2.0,
        numlevels: int = 8,
) -> (np.ndarray, np.ndarray):
    """Computes a bandpass decomposition of a temporal signal based on 
    differences between temporal scale-space representations generated 
    by convolution with discrete approximations of the time-causal limit 
    kernel, leading to the DoT bandpass representation.
    """
    # Compute the underlying time-causal temporal scale-space representation
    tempscsp, _ = \
    limitkernfilt_mult(signal, stddevmin, stddevmax, c, numlevels)

    # Compute the bandpass representations with special treatment of the first
    numscales = tempscsp.shape[0]
    bandpass = np.zeros(tempscsp.shape)
    bandpass[0] = tempscsp[0] - signal
    for counter in range(1, numscales):
        bandpass[counter] = tempscsp[counter] - tempscsp[counter-1]

    # Return the last smoothed level for later reconstruction
    lastlevel = tempscsp[numscales-1]

    return bandpass, lastlevel


def reconstr_from_bandpass_DoT(
        bandpass: np.ndarray,
        lastlevel: np.ndarray
) -> np.ndarray:
    """Reconstructs the original signal from a bandpass DoT representation,
    given complementary access to the temporal scale-space representation
    at the coarsest temporal scale used for computing the bandpass DoT
    representations.
    """
    reconstr = lastlevel
    numscales = bandpass.shape[0]
    for counter in range(0, numscales):
        reconstr = reconstr - bandpass[counter]

    return reconstr


def distr_sc_levels(
        stddevmin: float,
        stddevmax: float,
        c: float = 2.0
) -> np.ndarray:
    """Distributes a set of scale levels between stddevmin and stddevmax
    using the scale ratio c between adjacent scale levels.
    """
    numscales = ceil(log(stddevmax/stddevmin, c))

    return stddevmin * (c ** np.linspace(0, numscales-1, numscales))


def bandpass_DoG(
        signal,
        stddevmin: float,
        stddevmax: float,
        c: float = 2.0,
        epsilon: float = 0.000001
) -> (np.ndarray, np.ndarray):
    """Computes a bandpass decomposition of a temporal signal based on 
    differences between temporal scale-space representations generated 
    by convolution with discrete approximations of the time-causal limit 
    kernel, leading to the DoT bandpass representation.
    """
    # Distribute a set of scale levels over the range
    sigmas = distr_sc_levels(stddevmin, stddevmax, c)

    # Compute the underlying non-causal scale-space representation
    numscales = sigmas.shape[0]
    tempscsp = np.zeros((numscales, signal.shape[0]))
    for counter in range(0, numscales):
        tempscsp[counter] = discgaussconv(signal, sigmas[counter], epsilon)

    # Compute the bandpass representations with special treatment of the first
    numscales = tempscsp.shape[0]
    bandpass = np.zeros(tempscsp.shape)
    bandpass[0] = tempscsp[0] - signal
    for counter in range(1, numscales):
        bandpass[counter] = tempscsp[counter] - tempscsp[counter-1]

    # Return the last smoothed level for later reconstruction
    lastlevel = tempscsp[numscales-1]

    return bandpass, lastlevel


def reconstr_from_bandpass_DoG(
        bandpass: np.ndarray,
        lastlevel: np.ndarray
) -> np.ndarray:
    """Reconstructs the original signal from a bandpass DoG representation,
    given complementary access to the temporal scale-space representation
    at the coarsest temporal scale used for computing the bandpass DoG
    representations.
    """
    # The method is structurally identical to the reconstruction
    # from the DoT representation
    return reconstr_from_bandpass_DoT(bandpass, lastlevel)


def bandpass_DoE(
        signal,
        stddevmin: float,
        stddevmax: float,
        c: float = 2.0
) -> (np.ndarray, np.ndarray):
    """Computes a bandpass decomposition of a temporal signal based on 
    differences between temporal scale-space representations generated 
    by convolution with discrete approximations of the time-causal limit 
    kernel, leading to the DoT bandpass representation.
    """
    # Distribute a set of scale levels over the range
    sigmas = distr_sc_levels(stddevmin, stddevmax, c)

    # Compute the underlying single scale channels
    numscales = sigmas.shape[0]
    tempscsp = np.zeros((numscales, signal.shape[0]))
    for counter in range(0, numscales):
        # Compute the time constant for the recursive filter
        tau = sigmas[counter]**2
        mu = (-1 + sqrt(1 + 4 * tau)) / 2
        # Set up the parameters for the recursive filter
        a = [1 + mu, -mu]
        b = [1.0]
        tempscsp[counter] = lfilter(b, a, signal)

    # Compute the bandpass representations with special treatment of the first
    numscales = tempscsp.shape[0]
    bandpass = np.zeros(tempscsp.shape)
    bandpass[0] = tempscsp[0] - signal
    for counter in range(1, numscales):
        bandpass[counter] = tempscsp[counter] - tempscsp[counter-1]

    # Return the last smoothed level for later reconstruction
    lastlevel = tempscsp[numscales-1]

    return bandpass, lastlevel


def reconstr_from_bandpass_DoE(
        bandpass: np.ndarray,
        lastlevel: np.ndarray
) -> np.ndarray:
    """Reconstructs the original signal from a bandpass DoE representation,
    given complementary access to the temporal scale-space representation
    at the coarsest temporal scale used for computing the bandpass DoE
    representations.
    """
    # The method is structurally identical to the reconstruction
    # from the DoT representation
    return reconstr_from_bandpass_DoT(bandpass, lastlevel)
