"""Temporal Scale Selection Toolbox for Python

For performing characterizations of the scale selection properties for 
the temporal scale-space representation generated by convolution with
the time-causal limit kernel.

References:

Lindeberg (2025) "Time-causal and time-recursive wavelets", 
draft manuscript.

Lindeberg (2023) "A time-causal and time-recursive temporal scale-space 
representation of temporal signals and past time", 
Biological Cybernetics 117(1-2): 21-59.
"""

from math import sqrt, log, ceil, exp
import numpy as np
from scipy.ndimage import correlate1d

from pyscsp.discscsp import Lpnorm, mean1D
from pyscsp.gaussders import make1Dgaussderfilter
from pyscsp.scsel import interpolparextr
from pytempscsp.tempscsp import deltafcn1D, limitkernfilt, limitkernfilt_mult


def sigmaarray8() :
    return np.exp(np.linspace(log(0.5), log(8.0), 80))


def limitkern_der(
        stddev : float,
        derorder : int,
        gamma : float = 1.0,
        c: float = 2.0,
        numlevels: int = 8,
        length : int = -17
) -> np.ndarray:
    """Computes the discrete approximation of the derivative of the
    time-causal limit kernel of order derorder, with the scale parameter
    in terms of the standard deviation stddev of the kernel"""
    if length < 0:
        length = 10 * ceil(1 + stddev)

    deltafcn = deltafcn1D(length)
    limitkernel = limitkernfilt(deltafcn, stddev, c, numlevels)

    if derorder == 0:
        return limitkernel

    if derorder == 1:
        dt = np.array([0,-1, 1])
        return stddev**gamma * correlate1d(np.roll(limitkernel, 1), dt)

    if derorder == 2:
        dtt = np.array([0, 0, 1, -2, 1])
        return stddev**(2*gamma) * correlate1d(np.roll(limitkernel, 2),dtt)

    raise ValueError(f"Not implemented for order {derorder}")


def limitkern_lpnorm(
        stddev : float,
        derorder : int,
        p : float = 1.0,
        gamma : float = 1.0,
        c: float = 2.0,
        numlevels: int = 8,
        length : int = -17
) -> np.ndarray:
    """Computes the discrete lp-norm of a discrete approximations of the
    derivative of the time-causal limit kernel of order derorder and at 
    temporal scale stddev, measured in units of the standard deviation of
    the time-causal limit kernel."""

    derkernel = \
      limitkern_der(stddev, derorder, gamma, c, numlevels, length)

    return Lpnorm(derkernel, p)


def tempder(
        signal,
        derorder : int
) -> np.ndarray:
    """Computes the temporal difference of order derorder of a signal"""

    if derorder == 0:
        return signal

    if derorder == 1:
        dt = np.array([-1, +1, 0])
        return correlate1d(signal, dt)

    if derorder == 2:
        dtt = np.array([1, -2, 1, 0, 0])
        return correlate1d(signal, dtt)

    raise ValueError(f"Not implemented for order {derorder}")


def map_limitkern_lpnorm(
        stddevvec : np.ndarray,
        derorder : int,
        p : float = 1.0,
        gamma : float = 1.0,
        c: float = 2.0,
        numlevels: int = 8,
        length : int = -17
) -> np.ndarray:
    """Computes the discrete lp-norm of a discrete approximations of the
    derivative of the time-causal limit kernel of order derorder and for 
    an array with values of the standard deviation stddev of the 
    time-causal limit kernel."""
    out = np.zeros(len(stddevvec))

    for i, stddev in np.ndenumerate(stddevvec):
        out[i] = \
          limitkern_lpnorm(stddev, derorder, p, gamma, c, numlevels, length)

    return out


def limitkernders_mult(
        signal,
        stddevmin : float,
        stddevmax : float,
        derorder : int,
        gamma : float = 1.0,
        c: float = 2.0,
        numlevels: int = 8
) -> (np.ndarray, np.ndarray):
    """Computes the scale-normalized derivative of order derorder for the
    scale normalization power gamma over multiple scales in the range
    [stddevmin, stddevmax] of the time-causal temporal scale-space 
    representation of a signal.

    The scale parameter stddev is expressed in units of the standard deviation 
    of the temporal scale-space kernel, corresponding the square root of
    the parameter tau in the scientific papers, which is expressed in units
    of the variance of the temporal scale-space kernel.

    The distribution parameter c should be strictly > 1, where a larger value
    leads to a more sparse sampling of the temporal scale levels implying
    less computational work, and also shorter temporal delays, whereas a
    smaller value of c leads to a denser sampling of the temporal scale
    levels at the costs of more computational work and longer temporal delays.

    Note: The length of the signal over the temporal domain is truncated
    by truncate = 4 units at the end, to avoid wraparound effects of the
    correlation function used for computing the temporal derivatives.
    Thereby, the symmetry of the signal is broken. If you need to maintain
    symmetry with respect to a central origin, then use the companion
    function limitkernders_mult_symm() instead.
    """
    truncate = 4

    tempscsp, sigmas = \
      limitkernfilt_mult(signal, stddevmin, stddevmax, c, numlevels)

    outarray = np.zeros(tempscsp.shape)

    for layer, sigma in np.ndenumerate(sigmas):
        outarray[layer, :] = \
          sigma**(gamma*derorder) * tempder(tempscsp[layer, :], derorder)

    return outarray[:, :-truncate], sigmas


def limitkernders_mult_symm(
        signal,
        stddevmin : float,
        stddevmax : float,
        derorder : int,
        gamma : float = 1.0,
        c: float = 2.0,
        numlevels: int = 8
) -> (np.ndarray, np.ndarray):
    """Performs a similar operation as the function limitkernders_mult(),
    however, with the important difference that truncation by 4 units 
    is also performed at the lower end, to maintain a symmetric origin 
    for processed signal.
    """
    truncate = 4

    outarray, sigmas = \
      limitkernders_mult(signal, stddevmin, stddevmax, \
                         derorder, gamma, c, numlevels)

    return outarray[:, truncate:], sigmas


def globscspmax(
        tempscsprepr : np.ndarray,
        sigmavec : np.ndarray
)-> (float, float):
    """Determines the global scale-space extremum in a temporal 
    scale-space representation of a scale-normalized temporal 
    derivate, assumed to have been computed with either of the
    functions limitkernders_mult() or limitkernders_mult_symm().

    The result is interpolated to subquantization accuracy, by
    parabolic interpolation along each dimension.
    """
    sigmaindex, tindex = \
      np.unravel_index(np.argmax(tempscsprepr, axis=None), \
                       tempscsprepr.shape)

    # Interpolate in the scale direction
    scspsign = tempscsprepr[:, tindex]
    if sigmaindex in (0, len(scspsign) - 1):
        sigmahat = sigmavec[sigmaindex]
    else:
        i = sigmaindex
        logsigma = np.log(sigmavec)
        logscale, _ = \
          interpolparextr(logsigma[i-1], logsigma[i], logsigma[i+1], \
                          scspsign[i-1], scspsign[i], scspsign[i+1])
        sigmahat = exp(logscale)

    # Interpolate in the temporal direction
    atscale = tempscsprepr[sigmaindex, :]
    if tindex in (0, len(atscale) - 1):
        that = tindex
    else:
        i = tindex
        that , _ = \
          interpolparextr(i-1, i, i+1, \
                          atscale[i-1], atscale[i], atscale[i+1])

    return float(sigmahat), float(that)


def gaussblobtempscaleest(
        sigmaref : float,
        sigmamin : float = 0.125,
        sigmamax : float = 64,
        gamma : float = 0.75,
        c : float = 2,
        length : int = -1,
        numlevels: int = 8
) -> (float, float) :
    """Computes a scale selection estimate based on the global extremum
    over scale of the second-order temporal derivative for the
    scale normalization power gamma, based on a temporal temporal scale-space
    representation obtained by convolution with a discrete approximation
    of the time-causal limit kernel for distribution parameter c
    applied to an idealized model of a blob of duration sigmaref.
    """
    # Estimate a default length of the signal
    if length < 0:
        length = 10 * ceil(1 + sigmaref)

    # Generate the idealized model signal
    model = -make1Dgaussderfilter(1, sigmaref, length, 'discgaussder')

    # Compute the time-causal scale-space representation
    derorder = 2
    tempscsprepr, sigmavec = \
      limitkernders_mult_symm(model, sigmamin, sigmamax, derorder, \
                              gamma, c, numlevels)

    # Detect the global scale-space maximum
    sigmahat, that = globscspmax(tempscsprepr, sigmavec)

    # Relate the delay to a centered coordinate system
    delay = that - length

    return sigmahat, delay


def mapgaussblobtempscaleest(
        sigmavec : np.ndarray,
        sigmamin : float = 0.125,
        sigmamax : float = 64,
        gamma : float = 0.75,
        c : float = 2,
        length : int = -1,
        numlevels: int = 8
) -> (float, float) :
    """Computes scale estimates for an idealized discrete Gaussian blob model
    for an array with values of the standard deviation sigma.
    """
    out = np.zeros(len(sigmavec))

    for i, sigma in np.ndenumerate(sigmavec):
        out[i], _ = \
          gaussblobtempscaleest(sigma, sigmamin, sigmamax, \
                                gamma, c, length, numlevels)

    return out


def mapgaussblobtempdelayest(
        sigmavec : np.ndarray,
        sigmamin : float = 0.125,
        sigmamax : float = 64,
        gamma : float = 0.75,
        c : float = 2,
        length : int = -1,
        numlevels: int = 8
) -> (float, float) :
    """Computes scale estimates for an idealized discrete Gaussian blob model
    for an array with values of the standard deviation sigma.
    """
    out = np.zeros(len(sigmavec))

    for i, sigma in np.ndenumerate(sigmavec):
        _, out[i] = \
          gaussblobtempscaleest(sigma, sigmamin, sigmamax, \
                                gamma, c, length, numlevels)

    return out


def gaussedgetempscaleest(
        sigmaref : float,
        sigmamin : float = 0.125,
        sigmamax : float = 64,
        gamma : float = 0.5,
        c : float = 2,
        length : int = -1,
        numlevels: int = 8
) -> (float, float) :
    """Computes a scale selection estimate based on the global extremum
    over scale of the first-order temporal derivative for the
    scale normalization power gamma, based on a temporal temporal scale-space
    representation obtained by convolution with a discrete approximation
    of the time-causal limit kernel for distribution parameter c
    applied to an idealized model of a edge of duration sigmaref.
    """
    # Estimate a default length of the signal
    if length < 0:
        length = 10 * ceil(1 + sigmaref)

    # Generate the idealized model signal
    model = np.cumsum(make1Dgaussderfilter(1, sigmaref, length, 'discgaussder'))

    # Compute the time-causal scale-space representation
    derorder = 1
    tempscsprepr, sigmavec = \
      limitkernders_mult_symm(model, sigmamin, sigmamax, derorder, \
                              gamma, c, numlevels)

    # Detect the global scale-space maximum
    sigmahat, that = globscspmax(tempscsprepr, sigmavec)

    # Relate the delay to a centered coordinate system
    delay = that - length

    return sigmahat, delay


def mapgaussedgetempscaleest(
        sigmavec : np.ndarray,
        sigmamin : float = 0.125,
        sigmamax : float = 64,
        gamma : float = 0.5,
        c : float = 2,
        length : int = -1,
        numlevels: int = 8
) -> (float, float) :
    """Computes scale estimates for an idealized discrete diffuse edge model
    for an array with values of the standard deviation sigma.
    """
    out = np.zeros(len(sigmavec))

    for i, sigma in np.ndenumerate(sigmavec):
        out[i], _ = \
          gaussedgetempscaleest(sigma, sigmamin, sigmamax, \
                                gamma, c, length, numlevels)

    return out


def mapgaussedgetempdelayest(
        sigmavec : np.ndarray,
        sigmamin : float = 0.125,
        sigmamax : float = 64,
        gamma : float = 0.5,
        c : float = 2,
        length : int = -1,
        numlevels: int = 8
) -> (float, float) :
    """Computes scale estimates for an idealized discrete diffuse edge model
    for an array with values of the standard deviation sigma.
    """
    out = np.zeros(len(sigmavec))

    for i, sigma in np.ndenumerate(sigmavec):
        _, out[i] = \
          gaussedgetempscaleest(sigma, sigmamin, sigmamax, \
                                gamma, c, length, numlevels)

    return out


def limitkern_mean(
        stddev : float,
        c: float = 2.0,
        numlevels: int = 8,
        length : int = -17
) -> float:
    """Computes the temporal mean of a discrete approximation of the
    derivative of the time-causal limit kernel of order derorder and at 
    temporal scale stddev, measured in units of the standard deviation of
    the time-causal limit kernel."""

    if length < 0:
        length = 10 * ceil(1 + stddev)

    deltafcn = deltafcn1D(length)
    limitkernel = limitkernfilt(deltafcn, stddev, c, numlevels)

    return mean1D(limitkernel)


def map_limitkern_mean(
        stddevvec : np.ndarray,
        c: float = 2.0,
        numlevels: int = 8,
        length : int = -17
) -> np.ndarray:
    """Computes the temporal mean of discrete approximations of the
    derivative of the time-causal limit kernel of order derorder and for 
    an array with values of the standard deviation stddev of the 
    time-causal limit kernel."""
    out = np.zeros(len(stddevvec))

    for i, stddev in np.ndenumerate(stddevvec):
        out[i] = \
          limitkern_mean(stddev, c, numlevels, length)

    return out


def limitkern_tmax(
        stddev : float,
        c: float = 2.0,
        numlevels: int = 8,
        length : int = -17
) -> float:
    """Computes the position of the temporal maximum of a discrete approximation 
    of the derivative of the time-causal limit kernel of order derorder and at 
    temporal scale stddev, measured in units of the standard deviation of
    the time-causal limit kernel."""

    if length < 0:
        length = 10 * ceil(1 + stddev)

    deltafcn = deltafcn1D(length)
    limitkernel = limitkernfilt(deltafcn, stddev, c, numlevels)

    tindex = np.argmax(limitkernel)
    #globarrindex = np.argmax(limitkernel)
    #tindex = \
    #  np.unravel_index(np.argmax(limitkernel, axis=None), \
    #                   limitkernel.shape)

    # Interpolate in the temporal direction
    if tindex in (0, len(limitkernel) - 1):
        that = tindex
    else:
        i = tindex
        that , _ = \
          interpolparextr(i-1, i, i+1, \
                          limitkernel[i-1], limitkernel[i], limitkernel[i+1])

    return float(that)


def map_limitkern_tmax(
        stddevvec : np.ndarray,
        c: float = 2.0,
        numlevels: int = 8,
        length : int = -17
) -> np.ndarray:
    """Computes the position of the temporal maximum of discrete approximations 
    of the derivative of the time-causal limit kernel of order derorder and for 
    an array with values of the standard deviation stddev of the 
    time-causal limit kernel."""
    out = np.zeros(len(stddevvec))

    for i, stddev in np.ndenumerate(stddevvec):
        out[i] = \
          limitkern_tmax(stddev, c, numlevels, length)

    return out


def contlimitkern_mean(
        stddev : float,
        c: float = 2.0
) -> np.ndarray:
    """Returns the temporal mean of the continuous time-causal limit kernel
    according to Equation (34) in 

    Lindeberg (2016) "Time-causal and time-recursive spatio-temporal receptive 
    fields", Journal of Mathematical Imaging and Vision 55(1): 50-88.
    """
    return sqrt((c + 1)/(c - 1)) * stddev


def map_contlimitkern_mean(
        stddevvec : np.ndarray,
        c: float = 2.0
) -> np.ndarray:
    """Returns the temporal mean of the continuous time-causal limit kernel for 
    an array with values of the standard deviation stddev of the 
    time-causal limit kernel."""
    out = np.zeros(len(stddevvec))

    for i, stddev in np.ndenumerate(stddevvec):
        out[i] = \
          contlimitkern_mean(stddev, c)

    return out


def contlimitkern_tmax(
        stddev : float,
        c: float = 2.0
) -> np.ndarray:
    """Returns an estimate of the the temporal mean of the continuous 
    time-causal limit kernel according to Equation (39) in

    Lindeberg (2023) "A time-causal and time-recursive scale-covariant
    scale-space representation of temporal signals and past time", 
    Biological Cybernetics, 117(1-2): 21-59.
    """
    return ((c + 1)**2 * stddev)/(2 * sqrt(2) * sqrt((c - 1) * c**3))


def map_contlimitkern_tmax(
        stddevvec : np.ndarray,
        c: float = 2.0
) -> np.ndarray:
    """Returns the temporal mean of the continuous time-causal limit kernel for 
    an array with values of the standard deviation stddev of the 
    time-causal limit kernel."""
    out = np.zeros(len(stddevvec))

    for i, stddev in np.ndenumerate(stddevvec):
        out[i] = \
          contlimitkern_tmax(stddev, c)

    return out
